### ISSUE TITLE
capture not working

### ISSUE THREAD

**Issue by redfox-gx** [GammaDeltaII/4PlayerChess#4]
**Describe the bug**
long range capture not accepted 
board state: 3yRyNyByKyQyByNyR3/4yPyPyPyPyPyPyP3/14/bRbP7gP3gR/bNbP1yP8gPgN/bBbP10gPgB/bKbP10gPgQ/bQbP10gPgK/bBbP10gPgB/bN2bP8gPgN/bR11gR1/3rR10/4rPrPrPrPrPrPrP3/4rNrBrQrKrB1rR3 b rKbKbQyKyQgQ - 13 4

**To Reproduce**
1. d2d3 b4c4 d13d12 m11k11
2. Nj1k3 c4xd3 d12d11 k11j11
3. Nk3xm4 b5d5 d11d10 Rn4xm4
4. _blue rook to capture green rook, but move not allowed_

**Expected behavior**
expected capture to work

**Please report:**
windows 
no error message

**Comment by GammaDeltaII** [comment]
This is not a bug. Note that the application only supports the Teams variant, not Free-For-All. Blue and Green are teammates. Capturing friendly pieces is not possible.
